# Generated by Django 5.2.6 on 2025-09-26 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilidades', '0001_initial'),
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('valor', models.JSONField(blank=True, default=dict)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agregados', to='facilidades.condominio')),
            ],
            options={
                'verbose_name': 'Agregado',
                'verbose_name_plural': 'Agregados',
                'db_table': 'agregados',
            },
        ),
        migrations.CreateModel(
            name='PrediccionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('morosidad', 'Morosidad'), ('consumo', 'Consumo'), ('anomaly', 'Anomalía')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('version_modelo', models.CharField(default='v1', max_length=50)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_ia', to='facilidades.unidad')),
            ],
            options={
                'verbose_name': 'Predicción IA',
                'verbose_name_plural': 'Predicciones IA',
                'db_table': 'predicciones_ia',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionRecurrente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cron', models.CharField(help_text='Expresión cron para ejecución', max_length=100)),
                ('siguiente_ejecucion', models.DateTimeField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_recurrentes', to='facilidades.unidad')),
            ],
            options={
                'verbose_name': 'Programación Recurrente',
                'verbose_name_plural': 'Programaciones Recurrentes',
                'db_table': 'programaciones_recurrentes',
            },
        ),
    ]
