# Generated by Django 5.2.6 on 2025-09-26 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMorosidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Lista de residentes con pagos pendientes')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_morosidad', to='facilidades.condominio')),
            ],
            options={
                'verbose_name': 'Reporte de Morosidad',
                'verbose_name_plural': 'Reportes de Morosidad',
                'db_table': 'reportes_morosidad',
            },
        ),
    ]
