# Generated by Django 5.2.6 on 2025-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('residente', 'Residente'), ('junta', 'Junta Directiva'), ('guardia', 'Guardia')], default='residente', max_length=20),
        ),
    ]
