# Generated by Django 5.2.6 on 2025-09-28 23:58

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_photo_upload_to),
        ),
    ]
