# Generated by Django 5.2.6 on 2025-09-29 00:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
