# Generated by Django 5.2.6 on 2025-09-25 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.TextField(blank=True, null=True)),
                ('pais', models.TextField(blank=True, null=True)),
                ('zona_horaria', models.TextField(blank=True, null=True)),
                ('moneda', models.TextField(blank=True, null=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
                'db_table': 'condominios',
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner_type', models.TextField(blank=True, null=True)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('url', models.TextField()),
                ('mime', models.TextField(blank=True, null=True)),
                ('tamanio', models.BigIntegerField(blank=True, null=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'db_table': 'adjuntos',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('reportado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_progreso', 'En progreso'), ('cerrada', 'Cerrada')], default='abierta', max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('ubicacion', models.JSONField(blank=True, null=True)),
                ('urls_audio', models.JSONField(blank=True, null=True)),
                ('urls_imagen', models.JSONField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='facilidades.condominio')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencias',
            },
        ),
        migrations.CreateModel(
            name='ComentarioIncidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.TextField()),
                ('adjuntos', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='facilidades.incidencia')),
            ],
            options={
                'verbose_name': 'Comentario de incidencia',
                'verbose_name_plural': 'Comentarios de incidencias',
                'db_table': 'comentarios_incidencia',
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.TextField()),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('reglas', models.JSONField(blank=True, default=dict)),
                ('ventana_reserva_dias', models.IntegerField(default=30)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='facilidades.condominio')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'db_table': 'instalaciones',
            },
        ),
        migrations.CreateModel(
            name='IndisponibilidadInstalacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='facilidades.instalacion')),
            ],
            options={
                'verbose_name': 'Indisponibilidad de instalación',
                'verbose_name_plural': 'Indisponibilidades',
                'db_table': 'indisponibilidad_instalacion',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_unidad', models.TextField()),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo', models.CharField(choices=[('departamento', 'Departamento'), ('local', 'Local'), ('cochera', 'Cochera')], default='departamento', max_length=30)),
                ('estado', models.CharField(choices=[('ocupado', 'Ocupado'), ('vacante', 'Vacante'), ('en_venta', 'En venta'), ('mantenimiento', 'Mantenimiento')], default='ocupado', max_length=30)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='facilidades.condominio')),
                ('ocupante_actual_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocupaciones', to=settings.AUTH_USER_MODEL)),
                ('propietario_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidades',
                'unique_together': {('condominio', 'numero_unidad')},
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='facilidades.unidad'),
        ),
        migrations.CreateModel(
            name='ResidentesUnidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rol', models.CharField(default='propietario', help_text='propietario|inquilino|ocupante', max_length=30)),
                ('desde', models.DateField(blank=True, null=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes_unidad', to='facilidades.unidad')),
            ],
            options={
                'verbose_name': 'Residente de unidad',
                'verbose_name_plural': 'Residentes por unidad',
                'db_table': 'residentes_unidad',
                'indexes': [models.Index(fields=['unidad', 'usuario'], name='residentes__unidad__834024_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=30)),
                ('invitados', models.IntegerField(default=0)),
                ('pase_qr', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='facilidades.instalacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='facilidades.unidad')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'indexes': [models.Index(fields=['instalacion', 'inicio', 'fin'], name='reservas_instala_ad6d46_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['condominio', 'estado'], name='incidencias_condomi_c66419_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['asignado_a'], name='incidencias_asignad_b3b313_idx'),
        ),
    ]
