# Generated by Django 5.2.6 on 2025-09-25 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlacePago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enlace', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expira_en', models.DateTimeField()),
                ('limite_uso', models.IntegerField(default=1)),
                ('sesion_pasarela', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(default='activo', max_length=30)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_pago', to='facilidades.condominio')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_creados', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_pago', to='facilidades.unidad')),
            ],
            options={
                'db_table': 'enlaces_pago',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('emitida_en', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='facilidades.condominio')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='facilidades.unidad')),
            ],
            options={
                'db_table': 'facturas',
                'ordering': ['-emitida_en'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='finanzas.factura')),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado_en', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(default='cash', max_length=30)),
                ('proveedor_pasarela', models.CharField(blank=True, max_length=50, null=True)),
                ('payload_pasarela', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(default='processing', max_length=30)),
                ('url_comprobante', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.factura')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facilidades.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
