# Generated by Django 5.2.6 on 2025-09-25 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilidades', '0001_initial'),
        ('users', '0003_vehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoAcceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.JSONField(blank=True, default=dict)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Punto de Acceso',
                'verbose_name_plural': 'Puntos de Acceso',
                'db_table': 'puntos_acceso',
            },
        ),
        migrations.CreateModel(
            name='AlertaPanico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='activo', max_length=30)),
                ('servicios_notificados', models.JSONField(blank=True, default=dict)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_panico', to='facilidades.unidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_panico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Pánico',
                'verbose_name_plural': 'Alertas de Pánico',
                'db_table': 'alertas_panico',
            },
        ),
        migrations.CreateModel(
            name='DeteccionPlaca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('placa_detectada', models.CharField(max_length=20)),
                ('camara_id', models.UUIDField()),
                ('capturado_en', models.DateTimeField()),
                ('imagen_url', models.TextField(blank=True, null=True)),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones_placas', to='facilidades.condominio')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detecciones', to='users.vehiculo')),
            ],
            options={
                'verbose_name': 'Detección de Placa',
                'verbose_name_plural': 'Detecciones de Placas',
                'db_table': 'detecciones_placas',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('denegado', 'Denegado')], max_length=30)),
                ('ocurrido_en', models.DateTimeField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('punto_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='seguridad.puntoacceso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_acceso', to='users.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'db_table': 'registros_acceso',
            },
        ),
        migrations.CreateModel(
            name='RegistroSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inicio_turno', models.DateTimeField()),
                ('fin_turno', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Seguridad',
                'verbose_name_plural': 'Registros de Seguridad',
                'db_table': 'registros_seguridad',
            },
        ),
    ]
