# Generated by Django 5.2.6 on 2025-09-26 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilidades', '0001_initial'),
        ('seguridad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteccionRostro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rostro_id', models.UUIDField(blank=True, help_text='Identificador único del rostro detectado', null=True)),
                ('imagen_url', models.TextField(blank=True, null=True)),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Embeddings u otros datos del modelo')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecciones_rostros', to='facilidades.condominio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detecciones_rostro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detección de Rostro',
                'verbose_name_plural': 'Detecciones de Rostros',
                'db_table': 'detecciones_rostros',
            },
        ),
    ]
